primary:
  background: '0xfafafa'
  foreground: '0x383a42'

normal:
  black: '0x383a42'
  red: '0xe45649'
  green: '0x50a14f'
  yellow: '0xc18401'
  blue: '0x0184bc'
  magenta: '0xa626a4'
  cyan: '0x0997b3'
  white: '0xfafafa'

bright:
  black: '0x383a42'
  red: '0xe45649'
  green: '0x50a14f'
  yellow: '0xc18401'
  blue: '0x0184bc'
  magenta: '0xa626a4'
  cyan: '0x0997b3'
  white: '0xfafafa'
